### ISSUE TITLE
Issue with nested route templates with flow-router

### ISSUE THREAD

**Issue by pronevich** [kadirahq/blaze-plus#4]
Can we use nested templates, like this? (base on flow-router-blaze-plus-example): 

``` html

<template name="post">
  <h3>Post Content</h3>
  {{#if $loaded}}
    {{#if $post}}
      <span>Post Title</span>: {{$post.title}}
      <div>
        {{> Template.dynamic template=nestedTemplate}}  // like so ?
        {{>$ template=nestedTemplate }}  // or like so ?
      </div>
    {{else}}
      Not Found
    {{/if}}
  {{else}}
    Loading...
  {{/if}}
</template>

```

And route:

``` javascript
FlowRouter.route('/settings', {
  action: function(params) {
    BlazeLayout.render('layout', {main: 'post', nestedTemplate: "settings"});
  }
});
```

Seems now it's impossible.

How to be when we have basic layout where in {{>$ template=main slug=prop$slug }}  changes our main templates and one of this templates 'settings' have tree tabs(buttons):  that change route and 'nested template in settings' ?

With blaze-layout and flow-router it's work perfect, but when added blaze-plus - no.

**Comment by arunoda** [comment]
You need to pass nestedTemplate here as a prop to to the `post` template.
I hope that's the way to do it here.

**Comment by pronevich** [comment]
Yes, it works, but re-render parent template unfortunately.
